# Generated by Django 3.0.7 on 2020-06-22 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amirlik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amirlik', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AmirlikYetki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amirlik_yetki', models.BooleanField(blank=True, choices=[(None, ''), (True, 'Var'), (False, 'Yok')], default=False, max_length=3)),
                ('amirlik_yetki_ismi', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Mudurluk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mudurluk', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MudurlukYetki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mudurluk_yetki', models.BooleanField(blank=True, choices=[(None, ''), (True, 'Var'), (False, 'Yok')], default=False, max_length=3)),
                ('mudurluk_yetki_ismi', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Yetki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yetki_tipi', models.CharField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200, unique=True)),
                ('sicil', models.IntegerField()),
                ('adres', models.TextField()),
                ('tc', models.CharField(max_length=11)),
                ('foto', models.ImageField(upload_to='')),
                ('mudurluk', models.CharField(max_length=200)),
                ('amirlik', models.CharField(blank=True, max_length=200)),
                ('amirlik_yetki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amir', to='fihrist.AmirlikYetki')),
                ('mudurluk_yetki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mudurluk', to='fihrist.MudurlukYetki')),
                ('yetki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yetkipersoneller', to='fihrist.Yetki')),
            ],
        ),
    ]
