# Generated by Django 3.0.7 on 2020-06-22 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fihrist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='amirlik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amirlikr', to='fihrist.Amirlik'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='amirlik_yetki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amirr', to='fihrist.AmirlikYetki'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='mudurluk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mudurlukr', to='fihrist.Mudurluk'),
        ),
        migrations.AlterField(
            model_name='personel',
            name='mudurluk_yetki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mudurr', to='fihrist.MudurlukYetki'),
        ),
    ]
